blank_issues_enabled: false
contact_links:
  - name: ğŸ’â€â™€ï¸ Help & support on Discord
    url: https://discord.com/invite/pJjQDQC
    about: You can contact us via Discord if you have any additional questions